### PR TITLE
Update kotlin, exposed and kotlinpoet versions

### LINKED ISSUE #50: Switch to Kotlin 1.5.x

### PR DESCRIPTION
**Pull request by ChristianSch**
fixes #50, #54. Tests are running, although I didn't handle any of the compiler warnings because they all are design decisions I couldn't make for you

### CODE REVIEW

**Comment by pjagielski** [comment]
Thanks! We have separate issue to eliminate depreciation warnings

**Comment by gurudatta-carbon** [comment]
is this change released ?

**Comment by pjagielski** [comment]
I think we'll release within a week

**Comment by gurudatta-carbon** [comment]
@pjagielski hello, checking if a new version can be released :)

**Comment by pjagielski** [comment]
Hi @gurudatta-carbon @ChristianSch I finally released 0.5.0, sorry for delay...

**Pull request merged**
